add support for output file in JSON format
briandfoy/cpan-audit pull request #24
Opened 2022-11-09 09:51 UTC by reneeb

Having the audit result in JSON format makes it easier to integrate cpan-audit in CI/CD pipelines or importing the results in other apps used to keep track of security issues (e.g. DefectDojo).

It doesn't print the JSON on the STDOUT as other log messages are already printed on STDOUT.

2022-11-09 19:30 UTC, briandfoy requested changes
This looks like a good start. Can you add documentation and tests?

2022-11-09 20:25 UTC, reneeb commented
Sure, will do that on Friday...

2022-11-11 13:46 UTC, reneeb commented
If I get it right, the failing test is caused by the new dependency File::Temp which has an advisory. Any ideas/suggestions what I can use instead?

2022-11-12 16:42 UTC, briandfoy commented
I can look at this after the weekend. Don't worry about the failing test for File::Temp.

Part of this comes from CPAN::Audit now looking at core modules too. There's a switch to turn that off, but there are a few other problems which are affecting this at the moment.

2022-11-15 09:49 UTC, briandfoy commented
@schelcj fixed some of the database problems, including the File::Glob issue I think. You can update the cpan-security-advisories submodule and try again. But, I think I can also merge this even if we haven't figured that out. I'll play with this later in the week and fix anything left over. 

You should be safe to use this locally though since I approve the changes. Everything looks good for now and I'll merge it once I make the tests work if you don't get to it first.

2022-11-28 10:49 UTC, reneeb commented
I've disabled this specific CVE...

2022-12-01 04:39 UTC, briandfoy commented
I've had a chance to play with this, and I'm looking at a few things that I think would be good changes overall and would be more suitable for JSON output.

My use case is this:

    cpan-audit installed | jq ...

- [ ] CPAN::Audit should create a common data structure and return that. cpan-audit can then decide how to format that. This means that nothing inside the modules knows or cares about JSON or any other format.
- [ ] JSON output should be able to go to standard output. If we have to turn all other output to stdout, that's something to consider. More likely, non-JSON output lines could be filtered out outside the script too.
- [ ] with that, the `--json` would be a boolean
- [ ] error output would also be json
- [ ] let's add a version key to the json

2022-12-01 04:57 UTC, briandfoy commented
Okay, I have a branch in briandfoy/json-output based off reneeb/json-output. There are a lot of changes. I need to look over it again to ensure it's good. `cpan-audit` acts almost the same, but responsibilities have moved around.

* Almost all output is deferred to cpan-audit, including error output. Big change, but we need the separation of concerns for future development. 
* Some options disappeared in CPAN::Audit->new since it no longer has responsibility for output
* Logging and other sorts of output now goes to STDERR, and STDOUT is reserved for the advisory output
* I added some stuff to the data structure so people looking at JSON output can get a little more info.
* I refactored a bunch of stuff because routines were getting too big

I still need to:

- [ ] Go back through the docs to make sure they line up with the changes (but there are no big user changes)

2022-12-01 06:17 UTC, reneeb commented
That sounds great. Thank you.

2023-01-04 21:02 UTC, briandfoy commented
This is released as CPAN-Audit 20230104.001 from #31

2023-01-04 21:02 UTC, closed without merging