implement modules command to audit a list of modules
briandfoy/cpan-audit pull request #45
Opened 2023-04-29 07:10 UTC by reneeb

As discussed in #28 it should be possible to pass a list of modules to cpan-audit. This PR adds a `modules` command:

```
cpan-audit modules Foo Bar
cpan-audit modules Foo "Bar;>4.0,<4.1"
```

2023-04-29 14:23 UTC, briandfoy commented
This could be better if one of these were true:

* the `module` command fixes up its arguments and calls whatever handles `modules` (probably easiest)
* `modules` is a wrapper around `module` that calls it several times and collects the results.

This way, both paths end up in the same code instead of diverging.

Also, this needs some tests.

2023-04-30 07:14 UTC, reneeb commented
I've changed the code to use the `module` code and I added tests

2023-05-01 03:57 UTC, briandfoy requested changes
One minor change. I might not get back to this right away, but everything looks good and this will go in.

2023-05-01 03:57 UTC, briandfoy commented on lib/CPAN/Audit.pm
> +			$self->verbose( "Module '$name' is not in database" );
This should use the string that `command_module` returns. There might be other errors.

2023-06-02 05:00 UTC, merged